### ISSUE TITLE
Links for language implementations are Github 404's

### ISSUE THREAD

**Issue by LeviSchuck** [miscreant/miscreant.github.io#1]
Hello, on https://miscreant.io/ the links for 
* Go: https://github.com/miscreant/miscreant.go/blob/master/README.md
* Javascript: https://github.com/miscreant/miscreant.js/tree/master/README.md
* Python: https://github.com/miscreant/miscreant.py/tree/master/README.md
* Ruby: https://github.com/miscreant/miscreant.rb/tree/master/README.md
* Rust: https://github.com/miscreant/miscreant.rs/tree/master/README.md
result in 404s.

The cause seems to be that the branch is called `develop`, but these links refer to `master`.

It works for miscreant.net as that has a `master` branch.

Best wishes

**Comment by tarcieri** [comment]
Thanks for reporting this! It should be corrected now.
